version: '3'
services:
  commander-api:
    build: .
    image: atarimonkacr.azurecr.io/commander-api
    ports:
      - "80:80"
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TUC:GR8?MHYP"
      MSSQL_PID: Express
    ports:
      - "1433:1433"